export const courseDetailData = [
  {
    id: "1",
    numer: "01",
    title: "Introduction to UI/UX Design",
    innertitle1: "Understanding UI/UX Design Principles",
    innnertext1: "Lesson 01",
    time1: "45 Minutes",
    innertitle2: "Importance of User-Centered Design",
    innnertext2: "Lesson 02",
    time2: "1 Hour",
    innertitle3: "Creating User Personas and Scenarios",
    innnertext3: "Lesson 03",
    time3: "2 Hour",
  },
  {
    id: "2",
    numer: "02",
    title: "Introduction to UI/UX Design",
    innertitle1: "Understanding UI/UX Design Principles",
    innnertext1: "Lesson 01",
    time1: "45 Minutes",
    innertitle2: "Importance of User-Centered Design",
    innnertext2: "Lesson 02",
    time2: "1 Hour",
    innertitle3: "Creating User Personas and Scenarios",
    innnertext3: "Lesson 03",
    time3: "2 Hour",
  },
  {
    id: "3",
    numer: "03",
    title: "Introduction to UI/UX Design",
    innertitle1: "Understanding UI/UX Design Principles",
    innnertext1: "Lesson 01",
    time1: "45 Minutes",
    innertitle2: "Importance of User-Centered Design",
    innnertext2: "Lesson 02",
    time2: "1 Hour",
    innertitle3: "Creating User Personas and Scenarios",
    innnertext3: "Lesson 03",
    time3: "2 Hour",
  },
  {
    id: "4",
    numer: "04",
    title: "Introduction to UI/UX Design",
    innertitle1: "Understanding UI/UX Design Principles",
    innnertext1: "Lesson 01",
    time1: "45 Minutes",
    innertitle2: "Importance of User-Centered Design",
    innnertext2: "Lesson 02",
    time2: "1 Hour",
    innertitle3: "Creating User Personas and Scenarios",
    innnertext3: "Lesson 03",
    time3: "2 Hour",
  },
  {
    id: "5",
    numer: "05",
    title: "Introduction to UI/UX Design",
    innertitle1: "Understanding UI/UX Design Principles",
    innnertext1: "Lesson 01",
    time1: "45 Minutes",
    innertitle2: "Importance of User-Centered Design",
    innnertext2: "Lesson 02",
    time2: "1 Hour",
    innertitle3: "Creating User Personas and Scenarios",
    innnertext3: "Lesson 03",
    time3: "2 Hour",
  },
];
